back:
  host: https://manuchap.herokuapp.com
  handle: wandering-valley-5544
  email: admin@studiowan.fr
  api_key: bb3be4f0209440288523f2b4ed6894fe2dd868d3

prod:
  host: https://engine.studiowan.fr
  handle: thoughtless-dove-695
  email: admin@studiowan.fr
  api_key: af3c8ca6fa3192b24cc6a1f6c1ba009084840570

home:
  host: http://0.0.0.0:3000
  handle: ecwid
  email: manuchap@gmail.com
  api_key: 3ab999631987ead74441fe9e8842c78ffc35ff88