name: Ecwid
locales: [en, fr]
domains: [ecwid.studiowan.fr]
timezone: UTC
seo_title:
  en: FreshFood
  fr: FraisManger
meta_keywords:
  en: ''
  fr: ''
meta_description:
  en: ''
  fr: ''
robots_txt: ''
metafields:
  shop:
    address: 700 South Laflin Street
    city: Chicago
    zip_code: '60607'
    country: US
    hours: Monday to Friday 9am-5pm
  theme:
    logo: ''
    link_color: ''
  social:
    facebook_id: locomotivecms
    twitter_id: locomotivecms
metafields_ui: {}
